name: Fetch Groupe 8 Football

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */17 * * *" # toutes les 6 heures

jobs:
  fetch_group8:
    name: Run Group 8 Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run Group 1 Analysis Script
        env:
          VPS_WEBHOOK: ${{ secrets.VPS_WEBHOOK }}
          SOFASCORE_COOKIE: ${{ secrets.SOFASCORE_COOKIE }}
        run: |
          echo "🚀 Démarrage de l’analyse du Groupe 8..."
          node scripts/fetch_group8.js
          echo "🏁 Fin du script Groupe 8."
