name: Fetch Group 11 volleyball Football

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */9 * * *" # toutes les 6 heures

jobs:
  fetch_group11:
    name: Run Group 11 volley Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run Group 1 Analysis Script
        env:
          VPS_WEBHOOK: ${{ secrets.VPS_WEBHOOK }}
          SOFASCORE_COOKIE: ${{ secrets.SOFASCORE_COOKIE }}
        run: |
          echo "🚀 Démarrage de l’analyse volley du Groupe 11..."
          node scripts/fetch_group11.js
          echo "🏁 Fin du script Groupe 11 volley."
