name: Fetch Groupe 3 Football

on:
  workflow_dispatch:
  schedule:
    - cron: "30 */12 * * *" # toutes les 6 heures

jobs:
  fetch_group3:
    name: Run Group 3 Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run Group 3 Analysis Script
        env:
          VPS_WEBHOOK: ${{ secrets.VPS_WEBHOOK }}
          SOFASCORE_COOKIE: ${{ secrets.SOFASCORE_COOKIE }}
        run: |
          echo "🚀 Démarrage de l’analyse du Groupe 3..."
          node scripts/fetch_group3.js
          echo "🏁 Fin du script Groupe 3."

