name: Fetch Group 3 Football

on:
  workflow_dispatch:
  schedule:
    - cron: "30 */13 * * *" # toutes les 10 heures

jobs:
  fetch_group3:
    name: Run Group 1 Script
    runs-on: self-hosted  # Self-hosted runner sur ton VPS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          # Installer les navigateurs Playwright sans apt-get
          npx playwright install chromium
          npx playwright install firefox
          npx playwright install webkit

      - name: Run Group 1 Analysis Script
        env:
          VPS_WEBHOOK: ${{ secrets.VPS_WEBHOOK }}
          
        run: |
          echo "Demarrage de l'analyse du Groupe 1..."
          node scripts/fetch_group3.js
          echo "Fin du script Groupe 1."
