
name: Fetch Groupe 2 Football

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # toutes les 6 heures

jobs:
  fetch_group4:
    name: Run Group  Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run Group 4 Analysis Script
        env:
          VPS_WEBHOOK: ${{ secrets.VPS_WEBHOOK }}
          SOFASCORE_COOKIE: ${{ secrets.SOFASCORE_COOKIE }}
        run: |
          echo "🚀 Démarrage de l’analyse du Groupe 4..."
          node scripts/fetch_group2.js
          echo "🏁 Fin du script Groupe 4."
